-- drop table if exists course CASCADE
-- drop table if exists course_associate CASCADE
-- drop table if exists student CASCADE
-- create table course (
--        courseid bigint generated by default as identity,
--         course_name varchar(255),
--         primary key (courseid)
--     )
--
--     create table course_associate (
--        student_id bigint not null,
--         course_id bigint not null,
--         primary key (student_id, course_id)
--     )
--
--     create table student (
--        studentid bigint generated by default as identity,
--         student_name varchar(255),
--         primary key (studentid)
--     )

    insert into student(studentid,student_name) values (101, 'John')
    insert into student(studentid,student_name) values (102, 'Peter')
    insert into student(studentid,student_name) values (103, 'Chris')

    insert into course(courseid, course_name) values (1001, 'Mathematics')
    insert into course(courseid, course_name)  values (1002, 'Computer Science')
    insert into course(courseid, course_name)  values (1003, 'Physics')
    insert into course(courseid, course_name)  values (1004, 'Chemistry')